CREATE TABLE IF NOT EXISTS Genres(
Genre_id SERIAL PRIMARY KEY,
name VARCHAR(60) NOT NULL);

CREATE TABLE IF NOT EXISTS Singers(
Singer_id SERIAL PRIMARY KEY,
name VARCHAR(60) NOT NULL);

CREATE TABLE IF NOT EXISTS Singer_Genre(
Genre_id INTEGER REFERENCES Genre(id),
Singer_id INTEGER REFERENCES Singer(id),
CONSTRAINT PR_K PRIMARY KEY (Genre_id, Singer_id));

CREATE TABLE IF NOT EXISTS Albums(
Album_id SERIAL PRIMARY KEY,
name VARCHAR(120) NOT NULL,
issue_date DATE,
CONSTRAINT chk_date CHECK (issue_date >= '2000-01-01'));

CREATE TABLE IF NOT EXISTS Album_Singer(
Singer_id INTEGER REFERENCES Singer(id),
Album_id INTEGER REFERENCES Album(id),
CONSTRAINT PK PRIMARY KEY (Singer_id, Album_id));

CREATE TABLE IF NOT EXISTS Collections(
Collection_id SERIAL PRIMARY KEY,
name VARCHAR(120) NOT NULL,
issue_date DATE,
CONSTRAINT chk_d CHECK (issue_date  >= '2000-01-01'));

CREATE TABLE IF NOT EXISTS Tracks(
Track_id SERIAL PRIMARY KEY,
id INT NOT NULL REFERENCES Album(id) ,
name VARCHAR(60) NOT NULL,
duration FLOAT NOT NULL);

CREATE TABLE IF NOT EXISTS Track_Collection(
Track_id INTEGER REFERENCES Track(id),
Collection_id INTEGER REFERENCES Collection(id),
CONSTRAINT PK_2 PRIMARY KEY (Track_id, Collection_id));
